CREATE TABLE IF NOT EXISTS baskets (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS basket_items (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    basket_id BIGINT NOT NULL,
    stock_code VARCHAR(20) NOT NULL,
    quantity DOUBLE NOT NULL,
    type VARCHAR(10) NOT NULL,
    executed BOOLEAN NOT NULL DEFAULT FALSE,
    executed_price DOUBLE DEFAULT NULL,
    FOREIGN KEY (basket_id) REFERENCES baskets(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS conditional_orders (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    code VARCHAR(20) NOT NULL,
    quantity DOUBLE NOT NULL,
    entry_price DOUBLE NOT NULL DEFAULT 0,
    stop_loss DOUBLE NOT NULL DEFAULT 0,
    take_profit DOUBLE NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    triggered VARCHAR(10) DEFAULT NULL,
    executed_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
