CREATE TABLE IF NOT EXISTS agent_mandates (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    persona_style VARCHAR(50) NOT NULL DEFAULT 'balanced',
    debate_rounds INT NOT NULL DEFAULT 1,
    risk_profile VARCHAR(30) NOT NULL DEFAULT 'moderate',
    max_position DECIMAL(5,2) NOT NULL DEFAULT 15,
    tickers_json LONGTEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
