CREATE TABLE IF NOT EXISTS custom_indices (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    stocks_json LONGTEXT NOT NULL,
    weights_json LONGTEXT NOT NULL DEFAULT '{}',
    base_value DECIMAL(15,2) DEFAULT 100,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
