[supervisord]
nodaemon=false
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:investo]
command=/opt/investo/investo-linux
directory=/opt/investo
autostart=true
autorestart=true
startretries=5
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/investo.log
stderr_logfile=/var/log/investo-error.log
environment=INVESTO_APP_ENV="production"
