"""Selector-level extraction of still-referenced rules from local Tailwind output.css."""
import pathlib, re

ROOT = pathlib.Path(r"D:\project laravel\investo")
tabler = set(re.findall(r"\.([a-z][a-z0-9-]+)", (ROOT / "web/static/css/vendor/tabler.css").read_text(encoding="utf-8")))
fintech = set(re.findall(r"\.([a-zA-Z][\w-]*)\s*[,{]", (ROOT / "web/static/css/fintech.css").read_text(encoding="utf-8")))
native = tabler | fintech

toks = set()
for base in ["web/templates", "web/static"]:
    for p in (ROOT / base).rglob("*.html"):
        t = p.read_text(encoding="utf-8", errors="replace")
        t = re.sub(r"\[\[.*?\]\]", " ", t)
        t = re.sub(r"<style[^>]*>.*?</style>", " ", t, flags=re.DOTALL)
        t = re.sub(r"<script[^>]*>.*?</script>", " ", t, flags=re.DOTALL)
        for m in re.finditer(r'class=(["\'])(.*?)\1', t, flags=re.DOTALL):
            for tok in re.split(r"\s+", m.group(2)):
                if tok:
                    toks.add(tok)


def css_escape(tok):
    return "".join(ch if (ch.isalnum() or ch in "-_") else "\\" + ch for ch in tok)


needles = set()
for tok in toks:
    if not re.match(r"^[a-zA-Z/_:.!\[\]-][\w/.:!\[\]#()%-]*$", tok):
        continue
    if tok[0] in ("[", "{", "'", '"', ".", "$", "!", "(", "#", "<", ">", "/"):
        continue
    if "?" in tok or "&&" in tok or "||" in tok:
        continue
    needles.add("." + css_escape(tok))

css = (ROOT / "web/static/css/output.css").read_text(encoding="utf-8")

RULE = re.compile(r"([^{}@]+)\{([^{}]*)\}")


def keep_rule(selector):
    # match if any needle appears as full selector component.
    # Pseudo/state variants (dark:/hover:/disabled:/...) are ALWAYS kept:
    # Tabler has no such variants, so these rules are the compat layer's purpose.
    # Plain duplicates of native Tabler/fintech classes are skipped.
    for nd in needles:
        if nd in selector:
            # derive core class: strip leading dot + variant prefixes
            core = nd[1:]
            core = re.sub(r"\\(.)", r"\1", core)
            variant = None
            for pr in ("dark:hover:", "md:hover:", "lg:hover:", "dark:", "hover:",
                       "focus:", "sm:", "md:", "lg:", "xl:", "disabled:"):
                if core.startswith(pr):
                    variant = pr
                    core = core[len(pr):]
                    break
            core = re.sub(r"/\d+$", "", core)
            if variant is None and core in native:
                continue
            return True
    return False


# find @media spans
spans = []
for m in re.finditer(r"@media[^{]*\{", css):
    depth = 1
    i = m.end()
    while i < len(css) and depth:
        if css[i] == "{":
            depth += 1
        elif css[i] == "}":
            depth -= 1
        i += 1
    spans.append((m.start(), i, css[m.start():m.end() - 1]))

spans.sort()
out_parts = []
last = 0
covered = []


def emit_plain(chunk):
    for m in RULE.finditer(chunk):
        sel = m.group(1)
        if keep_rule(sel):
            out_parts.append(m.group(0))


pos = 0
for s, e, header in spans:
    emit_plain(css[pos:s])
    inner = css[css.find("{", s) + 1:e - 1]
    kept_inner = []
    for m in RULE.finditer(inner):
        if keep_rule(m.group(1)):
            kept_inner.append(m.group(0))
    if kept_inner:
        out_parts.append(header + "{" + "".join(kept_inner) + "}")
    pos = e
emit_plain(css[pos:])

# always keep @property + :root theme vars + keyframes referenced
for m in re.finditer(r"(@property[^{]*\{[^{}]*\}|@keyframes[^{]*\{(?:[^{}]*\{[^{}]*\}[^{}]*)*\})", css):
    out_parts.append(m.group(0))

seen = set()
uniq = []
for b in out_parts:
    if b not in seen:
        seen.add(b)
        uniq.append(b)
out = "/* legacy-compat: still-referenced local utilities (generated by scripts/extract-compat.py) */\n" + "".join(uniq)
(ROOT / "web/static/css/legacy-compat.css").write_text(out, encoding="utf-8")
print(f"rules={len(uniq)} size={len(out)//1024}KB needles={len(needles)}")
